# Generated by Django 3.2 on 2026-03-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventitem',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
