# Generated by Django 3.2 on 2026-03-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventitem_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventitem',
            old_name='paid',
            new_name='completed',
        ),
    ]
